#!/bin/sh
# Copyright (C) 2018 Wesley Tanaka
#
# This file is part of docker-alpine-37-uid-openjdk8-gradle
#
# docker-alpine-37-uid-openjdk8-gradle is free software: you can
# redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# docker-alpine-37-uid-openjdk8-gradle is distributed in the hope that
# it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with docker-alpine-37-uid-openjdk8-gradle.  If not, see
# <http://www.gnu.org/licenses/>.

# Use this script to launch a command line program inside the
# container, e.g.

set -e
set -x
CIDFILE=`mktemp tmp.XXXXXXXXXX`
rm -f "$CIDFILE"
WRAPPERDIR=`mktemp tmp.XXXXXXXXXX`
rm -f "$WRAPPERDIR"
docker run \
  -i -t \
  --cidfile="$CIDFILE" \
  -e "HOSTUID=`id -u`" \
  -e "HOSTGID=`id -g`" \
  wtanaka/alpine-37-uid-openjdk8-gradle \
  sh -c "mkdir $WRAPPERDIR; cd $WRAPPERDIR; /opt/gradle/bin/gradle wrapper $@"
docker cp $(cat $CIDFILE):/home/hostuser/$WRAPPERDIR .
mv $WRAPPERDIR/* .
docker rm $(cat $CIDFILE)
rm -f "$CIDFILE"
rm -rf $WRAPPERDIR
