#!/bin/sh
# Copyright (C) 2018 Wesley Tanaka
#
# This file is part of docker-xenial-uid
#
# docker-xenial-uid is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# docker-xenial-uid is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with docker-xenial-uid.  If not, see
# <http://www.gnu.org/licenses/>.

# Use this script to launch a command line program inside the
# container, e.g.

exec docker run \
  -i -t --rm \
  -e "HOSTUID=`id -u`" \
  -e "HOSTGID=`id -g`" \
  -v "`pwd`:/work" \
  -v "$HOME:/home/hostuser" \
  wtanaka/alpine-37-uid-openjdk8-gradle \
  /opt/gradle/bin/gradle "$@"
